import { z } from 'zod';

export const telemetrySummarySchema = z.object({
  event_type: z.literal('request_summary'),
  session_id: z.string(),
  turn_id: z.string(),
  request_group_id: z.string(),
  created_at: z.string(),
  started_at: z.string(),
  completed_at: z.string().nullable(),
  provider: z.enum(['openrouter', 'openai', 'anthropic']),
  model_requested: z.string(),
  model_resolved: z.string().nullable(),
  router: z.string().nullable(),
  generation_id: z.string().nullable(),
  provider_request_id: z.string().nullable(),
  upstream_id: z.string().nullable(),
  request_id: z.string().nullable(),
  provider_name: z.string().nullable(),
  provider_responses: z.array(z.unknown()).nullable(),
  streamed: z.boolean(),
  cancelled: z.boolean(),
  interrupted_by_user: z.boolean(),
  metadata_fetch_status: z.enum(['pending', 'success', 'failed', 'not_supported']),
  finish_reason: z.string().nullable(),
  native_finish_reason: z.string().nullable(),
  latency_ms: z.number().nullable(),
  generation_time_ms: z.number().nullable(),
  moderation_latency_ms: z.number().nullable(),
  time_to_first_token_ms: z.number().nullable(),
  prompt_tokens: z.number().nullable(),
  completion_tokens: z.number().nullable(),
  reasoning_tokens: z.number().nullable(),
  cached_tokens: z.number().nullable(),
  native_tokens_prompt: z.number().nullable(),
  native_tokens_completion: z.number().nullable(),
  native_tokens_reasoning: z.number().nullable(),
  native_tokens_cached: z.number().nullable(),
  total_cost: z.number().nullable(),
  upstream_inference_cost: z.number().nullable(),
  cache_discount: z.number().nullable(),
  task_type: z.string().nullable(),
  workflow_stage: z.string().nullable(),
  mode: z.string(),
  phase_at_send: z.string(),
  conversation_depth: z.number(),
  project_scoped: z.boolean(),
  attached_dirs_count: z.number(),
  artifact_generated: z.boolean(),
  artifact_type: z.string().nullable(),
  artifact_path: z.string().nullable(),
  user_message_length_chars: z.number(),
  assistant_response_length_chars: z.number(),
  follow_up_questions: z.number().nullable(),
  actionable_items_count: z.number().nullable(),
  complexity_score: z.number().nullable(),
  requires_followup: z.boolean().nullable(),
  context_summary_present: z.boolean(),
  recent_artifact_count: z.number(),
  prompt_context_length_chars: z.number(),
  error_kind: z.string().nullable(),
  error_message: z.string().nullable()
});
